import './globals.css';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Your access card to the financial markets',
  description: 'Generated by create next app',
}

const RootLayout = ({
  children,
}: {
  children: React.ReactNode
}) => {
  return (
    <html lang="en">
      <body className="">{children}</body>
    </html>
  )
}

export default RootLayout;